# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_parser', '0002_auto_20181015_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedata',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
